### ISSUE TITLE
I get an error when doing meteor npm install

### ISSUE THREAD

**Issue by antoninadert** [Herteby/grapher-vue-demo#1]
[2017-12-08T14_54_07_251Z-debug.log](https://github.com/Herteby/grapher-vue-demo/files/1542982/2017-12-08T14_54_07_251Z-debug.log)
I have this log when I tried to open it with `meteor npm install`

**Comment by Herteby** [comment]
Ah, it was some problem with package-lock.json. If you delete it it should work.
Btw, I just made a bunch of updates, you should pull the package again.

**Comment by antoninadert** [comment]
OK I got it working maybe you shouldn't commit this package.json file ! or at least tell to remove it in instructions.

Otherwise, I launched the beast, and it feels really good, thanks for providing this !!!

**Comment by Herteby** [comment]
You're supposed to include it to make sure that everyone uses exactly the same package versions. I removed it from this repo though, since it's just a simple demo anyway.
