### ISSUE TITLE
Cannot clone with git clone git@github.com:Herteby/graphical-grapher.git

### ISSUE THREAD

**Issue by antoninadert** [Herteby/grapher-vue-demo#2]
I cannot clone with git clone git@github.com:Herteby/graphical-grapher.git

it worked with https://github.com/Herteby/grapher-vue-demo.git

Do you assume I can get an SSH key ? If so how would I get one ?

**Comment by Herteby** [comment]
Ah yeah you need to have registered an SSH key with your GitHub account. That goes for all packages when you clone by SSH.

**Comment by antoninadert** [comment]
hahah yes sorry I managed to add a SSH key for the first time of my life !

Here was the guide https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/ 

I close this
